/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PortalClienteIdRouteImport } from './routes/portal.$clienteId'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedRefacoesRouteImport } from './routes/_authenticated/refacoes'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedPrecificacaoRouteImport } from './routes/_authenticated/precificacao'
import { Route as AuthenticatedPortalManagerRouteImport } from './routes/_authenticated/portal-manager'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedBriefingRouteImport } from './routes/_authenticated/briefing'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAtivosRouteImport } from './routes/_authenticated/ativos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PortalClienteIdRoute = PortalClienteIdRouteImport.update({
  id: '/portal/$clienteId',
  path: '/portal/$clienteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRefacoesRoute = AuthenticatedRefacoesRouteImport.update({
  id: '/refacoes',
  path: '/refacoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrecificacaoRoute =
  AuthenticatedPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalManagerRoute =
  AuthenticatedPortalManagerRouteImport.update({
    id: '/portal-manager',
    path: '/portal-manager',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBriefingRoute = AuthenticatedBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtivosRoute = AuthenticatedAtivosRouteImport.update({
  id: '/ativos',
  path: '/ativos',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/ativos': typeof AuthenticatedAtivosRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/portal-manager': typeof AuthenticatedPortalManagerRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/refacoes': typeof AuthenticatedRefacoesRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/portal/$clienteId': typeof PortalClienteIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/ativos': typeof AuthenticatedAtivosRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/portal-manager': typeof AuthenticatedPortalManagerRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/refacoes': typeof AuthenticatedRefacoesRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/portal/$clienteId': typeof PortalClienteIdRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ativos': typeof AuthenticatedAtivosRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/briefing': typeof AuthenticatedBriefingRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/portal-manager': typeof AuthenticatedPortalManagerRoute
  '/_authenticated/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/_authenticated/refacoes': typeof AuthenticatedRefacoesRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/portal/$clienteId': typeof PortalClienteIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ativos'
    | '/auditoria'
    | '/briefing'
    | '/clientes'
    | '/portal-manager'
    | '/precificacao'
    | '/projetos'
    | '/refacoes'
    | '/servicos'
    | '/portal/$clienteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/ativos'
    | '/auditoria'
    | '/briefing'
    | '/clientes'
    | '/portal-manager'
    | '/precificacao'
    | '/projetos'
    | '/refacoes'
    | '/servicos'
    | '/portal/$clienteId'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ativos'
    | '/_authenticated/auditoria'
    | '/_authenticated/briefing'
    | '/_authenticated/clientes'
    | '/_authenticated/portal-manager'
    | '/_authenticated/precificacao'
    | '/_authenticated/projetos'
    | '/_authenticated/refacoes'
    | '/_authenticated/servicos'
    | '/portal/$clienteId'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalClienteIdRoute: typeof PortalClienteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/$clienteId': {
      id: '/portal/$clienteId'
      path: '/portal/$clienteId'
      fullPath: '/portal/$clienteId'
      preLoaderRoute: typeof PortalClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/refacoes': {
      id: '/_authenticated/refacoes'
      path: '/refacoes'
      fullPath: '/refacoes'
      preLoaderRoute: typeof AuthenticatedRefacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/precificacao': {
      id: '/_authenticated/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof AuthenticatedPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal-manager': {
      id: '/_authenticated/portal-manager'
      path: '/portal-manager'
      fullPath: '/portal-manager'
      preLoaderRoute: typeof AuthenticatedPortalManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/briefing': {
      id: '/_authenticated/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof AuthenticatedBriefingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ativos': {
      id: '/_authenticated/ativos'
      path: '/ativos'
      fullPath: '/ativos'
      preLoaderRoute: typeof AuthenticatedAtivosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAtivosRoute: typeof AuthenticatedAtivosRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedBriefingRoute: typeof AuthenticatedBriefingRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedPortalManagerRoute: typeof AuthenticatedPortalManagerRoute
  AuthenticatedPrecificacaoRoute: typeof AuthenticatedPrecificacaoRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedRefacoesRoute: typeof AuthenticatedRefacoesRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAtivosRoute: AuthenticatedAtivosRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedBriefingRoute: AuthenticatedBriefingRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedPortalManagerRoute: AuthenticatedPortalManagerRoute,
  AuthenticatedPrecificacaoRoute: AuthenticatedPrecificacaoRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
  AuthenticatedRefacoesRoute: AuthenticatedRefacoesRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalClienteIdRoute: PortalClienteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
